# Generated by Django 4.0.5 on 2022-07-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ballot_poll_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='question_text',
            new_name='text',
        ),
    ]
